Dependency problem
rserdyukov/proctoring-bot pull request #23
Opened 2021-11-11 10:37 UTC by tenatarika

Настроил виртуальное окружение и создал скрипт для их установки. Установка зависимостей проекта в главное окружение Питона опасно, потому что может вызвать конфликт зависимостей. Я написал скрипт для установки Pipenv, создание виртуального окружения и установки зависимостей в него. 

Вячеслав  Д.

2021-11-12 20:09 UTC, NikitaZotov requested changes

2021-11-12 20:09 UTC, NikitaZotov commented on scripts/Pipfile
> +python_version = "3.9"
We use python 3.8 now. Are you sure that version 3.9 won't initiate some problems?

2021-11-12 20:09 UTC, NikitaZotov commented on scripts/Pipfile.lock
> +        "requires": {
You must not commit lock file.

2021-11-12 20:09 UTC, NikitaZotov commented on scripts/run_bot.sh
> +# pip3 install -r requirements.txt
There is no need to leave comments in the code.

2021-11-12 20:11 UTC, NikitaZotov commented
Make more represenatable commits names

2021-11-12 20:15 UTC, NikitaZotov commented
Specify PR name

2021-11-17 13:38 UTC, NikitaZotov requested changes

2021-11-17 13:38 UTC, NikitaZotov commented on .gitignore
> +Pipfile.lock
*/Pipfile.lock

2021-11-17 13:38 UTC, NikitaZotov commented on scripts/run_bot.sh
Odd space row

2021-11-17 13:39 UTC, NikitaZotov commented on scripts/Pipfile.lock
> +        "requires": {
Did you remove this file?

2021-11-18 20:04 UTC, NikitaZotov commented on .gitignore
> +Pipfile.lock
Correct commit title

2021-11-18 20:06 UTC, NikitaZotov commented
Check other conversations

2021-11-19 12:06 UTC, tenatarika commented
resolved conversations

2021-11-19 23:30 UTC, NikitaZotov requested changes
Rename commits titles

2021-11-23 11:48 UTC, closed without merging