Added menu and storage for works
rserdyukov/proctoring-bot pull request #58
Opened 2021-12-16 21:13 UTC by tenatarika

2021-12-18 19:14 UTC, NikitaZotov requested changes

2021-12-18 19:14 UTC, NikitaZotov commented on sources/bot/modules/chains/work/work_handlers_chain.py
> +class WorkHandlersChain(HandlersChain):
Is it better to name chain as "WorksHandlersChain"?

2021-12-18 19:14 UTC, NikitaZotov commented on sources/bot/modules/chains/work/work_handlers_chain.py
> +from bot.modules.handlers_registrar import HandlersRegistrar as Registrar
Set relative paths, please.

2021-12-18 19:14 UTC, NikitaZotov commented on sources/bot/storage/spreadsheet/works/works_spreadsheet_handler.py
> +            "works": ["username", "ФИО", "Группа", "Подгруппа", "Лабораторная работа"],
I think it is overkill because a student will be able to submit work if he is registered. It is better to take data from the table of information of registered users than to make a copy and store the group and subgroup again. Please. let's make two coloumns in this spreadsheet.

2021-12-20 21:17 UTC, tenatarika commented on sources/bot/storage/spreadsheet/works/works_spreadsheet_handler.py
> +            "works": ["username", "ФИО", "Группа", "Подгруппа", "Лабораторная работа"],
The name should remain because without a name it will not be possible to search in the table, for example to revise the work

2021-12-20 21:58 UTC, NikitaZotov approved these changes

2021-12-20 22:01 UTC, merged