Finished tests module
rserdyukov/proctoring-bot pull request #71
Opened 2021-12-21 15:58 UTC by VanderY

2021-12-21 16:02 UTC, NikitaZotov commented
Please rename commits names connected with merges.

2021-12-21 16:39 UTC, NikitaZotov requested changes

2021-12-21 16:39 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/student_handlers_chain.py
> +            # Проверка ответов на правильность
Please, translate comments in English.

2021-12-21 16:39 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/student_handlers_chain.py
> +                await callback_query.answer()
I think it is worth breaking this method down into several simpler ones.

2021-12-21 16:39 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/student_handlers_chain.py
> +        separated_data = callback_query.data.split(";")
What separated data is? Please, explain it.

2021-12-21 16:39 UTC, NikitaZotov commented on sources/bot/modules/factory/standard_handlers_factory.py
>  from ...modules.chains.main.main_handlers_chain import MainHandlersChain
Please, make correct order.

2021-12-21 16:39 UTC, NikitaZotov commented on sources/bot/storage/spreadsheet/tests/tests_spreadsheet_handler.py
> +        self._add_row(test_name + "_result", row, self._current_test_id)
I think it is worth breaking this method down into several simpler ones.

2021-12-21 16:39 UTC, NikitaZotov commented on sources/bot/storage/spreadsheet/tests/tests_spreadsheet_handler.py
> +        self._http_auth = ServiceAccountCredentials.from_json_keyfile_name(
We have a class that does this kind of logic. We were talking about it. Please, use it.

2021-12-21 16:39 UTC, NikitaZotov commented on sources/bot/storage/spreadsheet/tests/tests_spreadsheet_handler.py
> +                json.dump(test, f, ensure_ascii=False, indent=4)
Please, move the logic for working with json into a separate class.

2021-12-22 09:03 UTC, VanderY commented
Made new PR #73

2021-12-22 09:03 UTC, closed without merging