Survey module finished
rserdyukov/proctoring-bot pull request #73
Opened 2021-12-21 22:37 UTC by darkqq

1. Splitting large methods in current realisation into several small ones with single-place usage seems to me as not really good idea.
2. Comments have been translated.
3. Creation of custom spreadsheet_handler is conditioned by unnessesary constructor parameters in SpreadsheetHandler (such as new worksheet header attributes, static spreadsheet_id etc). Want to note that each of them is optional for each method and in our implementation, these parameters are simply not needed and would be just ignored -> SOLID is out of the question in this situation.

Hope you'll get me right.

If you have any questions or comments - I am opened for discussion.

2021-12-22 10:15 UTC, NikitaZotov requested changes

2021-12-22 10:15 UTC, NikitaZotov commented on sources/bot/modules/chains/main/main_handlers_chain.py
> +        await MainHandlersChain._wait_registration(message, state, not_registered)
You push old commits, replacing our new ones. Correct, please. Before making a pull request, you should always make sure that you have checked out the changes from the main repository.

2021-12-22 10:15 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/student_handlers_chain.py
> +                await callback_query.answer()
Split this method into the simplest ones.

2021-12-22 10:15 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/teacher_handlers_chain.py
> +                                 reply_markup=SurveyTeacherKeyboardBuilder.get_cancel_survey_keyboard())
Split this method into the simplest ones.

2021-12-22 10:15 UTC, NikitaZotov commented on sources/bot/modules/factory/standard_handlers_factory.py
>  from ...modules.chains.main.main_handlers_chain import MainHandlersChain
Make correct order of imports. Please, read code style convension.

2021-12-22 10:15 UTC, NikitaZotov commented on sources/bot/storage/spreadsheet/tests/tests_spreadsheet_handler.py
> +        return sheet_names
We don't needed in this spreadsheet handler. Please, use current one.

2021-12-22 10:15 UTC, NikitaZotov commented on sources/bot/storage/util/survey/test_to_json.py
> +                json.dump(test, f, ensure_ascii=False, indent=4)
Add blank row at the end of file.

2021-12-22 10:15 UTC, NikitaZotov commented on sources/bot/storage/util/survey/test_to_json.py
> +                json.dump(test, f, ensure_ascii=False, indent=4)
Are you implementing adapter pattern?

2021-12-22 13:55 UTC, darkqq commented on sources/bot/storage/spreadsheet/tests/tests_spreadsheet_handler.py
> +        return sheet_names
Почитай пиар месседж, я описал почему мы сделали данную реализацию и почему нам не подходит та, которая есть.

Динамическая генерация заголовков вашей реализацией просто не предусмотрена, а делать инитить каждый новый тест новый объект вашего хендлера бессмысленно, потому что код будет повторяться.

Даже солидом тут не прикроешься, в базовом классе просто бесполезная для нас реализация, использование которой в нашем случае тяжело представить.

2022-01-02 01:08 UTC, darkqq commented
Old PR was (mistakenly) closed due force-push to rollback commits.

2022-01-03 15:39 UTC, NikitaZotov requested changes

2022-01-03 15:39 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/student_handlers_chain.py
> +                                 reply_markup=SurveyStudentKeyboardBuilder.get_ready_to_survey_keyboard())
Please, specify code style.

2022-01-03 15:39 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/student_handlers_chain.py
> +            answers_kb = SurveyTeacherKeyboardBuilder.get_answers_keyboard(current_question, question_number,
Please, split this method.

2022-01-03 15:39 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/teacher_handlers_chain.py
> +                                 reply_markup=SurveyTeacherKeyboardBuilder.get_cancel_survey_keyboard())
Correct this one.

2022-01-03 15:39 UTC, NikitaZotov commented on sources/bot/storage/spreadsheet/tests/tests_spreadsheet_handler.py
> +                                                     valueInputOption="USER_ENTERED",
Remove this class and use existing the one.

2022-01-04 00:00 UTC, darkqq commented on sources/bot/storage/spreadsheet/tests/tests_spreadsheet_handler.py
> +                                                     valueInputOption="USER_ENTERED",
У нас другая логика работы класса. Нам не подходят статические хедеры таблицы. У нас идет работа не только с одной главной таблицей, но и с листами у спредщита. У вас в классе это не предусмотрено от слова совсем. Я могу сделать инит твоего хендлера, если так надо, но это просто бессмысленно.

2022-01-04 19:15 UTC, NikitaZotov requested changes

2022-01-04 19:15 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/student_handlers_chain.py
> +            await callback_query.answer()
This method is large. Please, split it into smaller ones.

2022-01-04 19:15 UTC, NikitaZotov commented on sources/bot/modules/chains/survey/teacher_handlers_chain.py
> +        return students, tests, test_name
Can you split this class into smaller ones? The smaller classes - the better.

2022-01-04 19:15 UTC, NikitaZotov commented on sources/bot/storage/spreadsheet/tests/tests_spreadsheet_handler.py
> +
Use existing handler and implement own one that will use existing handler.

2022-01-04 19:40 UTC, darkqq commented on sources/bot/modules/chains/survey/student_handlers_chain.py
> +            await callback_query.answer()
уже

2024-11-29 19:42 UTC, merged